version: '2'
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:pass@mysql:3306
      DATABASE_CLEANER_ALLOW_PRODUCTION: 'true'
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: 'true'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3000:3000'
    volumes:
      - $PWD:/usr/src/appdir
    links:
      - mysql

  mysql:
    image: mysql:5.7.10
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:1.15.7
    build: ./docker/nginx
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_USER: 'user_production'
      MYSQL_PASSWORD: 'user_password'
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - $PWD:/var/www
      - $PWD/docker/nginx/nginx_trapla.conf:/etc/nignx/conf.d/trapla.conf

volumes:
  mysql-data:
    driver: local
