version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - /share
      - ./docker/mysql/volumes:/var/lib/mysql

  server:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    volumes_from:
      - datastore
    depends_on:
      - datastore

  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb
    environment:
      RAILS_ENV: development
      DATABASE_CLEANER_ALLOW_PRODUCTION: 'true'
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: 'true'
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    volumes_from:
      - datastore
    depends_on:
      - db
    links:
      - db
      - db:database
      - db:mysql

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - '3306:3306'
    volumes_from:
      - datastore
    depends_on:
      - datastore
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
