default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: trapla_development
  username: user_develop
  password: PassDevelop0-

test:
  <<: *default
  database: trapla_test
  username: user_test
  password: PassTest0-

production:
  <<: *default
  database: trapla_production
  username: user_production
  password: PassProduction0-
