default: &default
  adapter: mysql2
  encoding: utf8
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: trapla_development
  username: user_develop
  password: PassDevelop0-

test:
  <<: *default
  database: trapla_test
  username: <%= ENV['DB_USERNAME'] || 'user_test' %>
  password: <%= ENV['DB_PASSWORD'] || 'PassTest0-' %>

production:
  <<: *default
  database: trapla_production
  username: user_production
  password: PassProduction0-
